In [1]:
# ndarry---> N-dimensional array
# vectorization ---> Apply operation to the entire array
# Broadcasting----> Automatic alignment of arrays with different shapes


In [2]:
# Introduction to Array
import numpy as np
data = np.array([[1.5,-0.1,3],[0,3,-6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. ,  3. , -6.5]])

In [3]:
data*10

array([[ 15.,  -1.,  30.],
       [  0.,  30., -65.]])

In [4]:
data + data

array([[  3. ,  -0.2,   6. ],
       [  0. ,   6. , -13. ]])

# Creating ndarrays

- From python sequences :np.array([1,2,3]) 
- Built-in generators: np.arange(),np.zeros(),np.ones(),np.linspace()
- Random Data : np.random.rand(),np.random.randit()

In [5]:
data1 = [6, 7.5, 8, 0, 1]


In [7]:
arr = np.array(data1)
arr

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [11]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [12]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

# Pandas

In [13]:
# Series
import numpy as np
import pandas as pd
obj = pd.Series([4,7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [14]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [15]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [17]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [18]:
obj2.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [19]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [20]:
# Concept of DataFrame in Pandas
# From dictionary to DataFrame
# Most common way: pass dict of list/Series
# keys---> column name
# values----> column data
# index automatically created(0,1,2...)
# Transpose (.T): swaps the rows and columns--useful for reshaping 


In [21]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
"year": [2000, 2001, 2002, 2001, 2002, 2003],
"pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

df = pd.DataFrame(data)

In [22]:
df

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9
5,Nevada,2003,3.2


In [23]:
df.head()

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9


In [24]:
df.tail()

,state,year,pop
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9
5,Nevada,2003,3.2


In [25]:
pd.DataFrame(data,columns = ['year','state','pop'])

,year,state,pop
0,2000,Ohio,1.5
1,2001,Ohio,1.7
2,2002,Ohio,3.6
3,2001,Nevada,2.4
4,2002,Nevada,2.9
5,2003,Nevada,3.2


In [26]:
df2 = pd.DataFrame(data,columns = ['years','state','pop','debt'])
df2

,years,state,pop,debt
0,NaN,Ohio,1.5,NaN
1,NaN,Ohio,1.7,NaN
2,NaN,Ohio,3.6,NaN
3,NaN,Nevada,2.4,NaN
4,NaN,Nevada,2.9,NaN
5,NaN,Nevada,3.2,NaN


In [28]:
df2['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [31]:
df2.years

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
Name: years, dtype: object

In [32]:
df2 = pd.DataFrame(data,columns = ['years','state','pop','debt'])

In [33]:
df2

,years,state,pop,debt
0,NaN,Ohio,1.5,NaN
1,NaN,Ohio,1.7,NaN
2,NaN,Ohio,3.6,NaN
3,NaN,Nevada,2.4,NaN
4,NaN,Nevada,2.9,NaN
5,NaN,Nevada,3.2,NaN


In [36]:
df2.iloc[1]

years     NaN
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [37]:
df2.loc[1:2]

,years,state,pop,debt
1,NaN,Ohio,1.7,NaN
2,NaN,Ohio,3.6,NaN


In [39]:
df2["eastern"] = df2["state"] == "Ohio"
df2

,years,state,pop,debt,eastern
0,NaN,Ohio,1.5,NaN,True
1,NaN,Ohio,1.7,NaN,True
2,NaN,Ohio,3.6,NaN,True
3,NaN,Nevada,2.4,NaN,False
4,NaN,Nevada,2.9,NaN,False
5,NaN,Nevada,3.2,NaN,False


In [40]:
del df2['eastern']

In [41]:
df2

,years,state,pop,debt
0,NaN,Ohio,1.5,NaN
1,NaN,Ohio,1.7,NaN
2,NaN,Ohio,3.6,NaN
3,NaN,Nevada,2.4,NaN
4,NaN,Nevada,2.9,NaN
5,NaN,Nevada,3.2,NaN


In [42]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6}, "Nevada": {2001: 2.4, 2002: 2.9}}


In [44]:
df3 = pd.DataFrame(populations)
df3

,Ohio,Nevada
2000,1.5,NaN
2001,1.7,2.4
2002,3.6,2.9


df3.T

In [45]:
df3.T

,2000,2001,2002
Ohio,1.5,1.7,3.6
Nevada,NaN,2.4,2.9


In [46]:
pd.DataFrame(populations, index=[2001, 2002, 2003])


,Ohio,Nevada
2001,1.7,2.4
2002,3.6,2.9
2003,NaN,NaN


In [47]:
df2.to_numpy()


array([[nan, 'Ohio', 1.5, nan],
       [nan, 'Ohio', 1.7, nan],
       [nan, 'Ohio', 3.6, nan],
       [nan, 'Nevada', 2.4, nan],
       [nan, 'Nevada', 2.9, nan],
       [nan, 'Nevada', 3.2, nan]], dtype=object)